# Generated by Django 6.0.4 on 2026-04-13 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tstatus',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Status'},
        ),
    ]
